version: "3.7"

services:
    api-gateway:
        build: .
        volumes:
            - .:/app
        networks:
            - main
        command: >
            bash -c "chmod +x ./mvnw 
            && ./mvnw spring-boot:run"
        ports:
            - "8765:8765"
        depends_on:
            - api-nameserver
        environment:
            - eureka.client.serviceUrl.defaultZone=http://api-nameserver:8761/eureka/
