version: "3.7"

services:
    api-nameserver:
        build:
            context: ./api-nameserver
            dockerfile: Dockerfile
        image: api-nameserver
        container_name: api-nameserver
        working_dir: /app
        volumes:
            - ./:/app
        networks:
            - main
        tty: true
        restart: always
        ports:
            - "8761:8761"
    api-gateway:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: api-gateway
        depends_on:
            - api-nameserver
    app-subscription-service:
        extends:
            file: ./app-subscription-service/docker-compose.override.yml
            service: app-subscription-service
        depends_on:
            - api-nameserver
    api-cache:
        extends:
            file: ./api-cache/docker-compose.override.yml
            service: api-cache
        depends_on:
            - api-nameserver
networks:
    main:
        driver: bridge
