version: "3.7"

services:
    api-nameserver:
        build:
            context: ./api-nameserver
            dockerfile: Dockerfile
        image: api-nameserver
        container_name: api-nameserver
        working_dir: /app
        volumes:
            - ./:/app
        networks:
            - main
        tty: true
        restart: always
        ports:
            - "8761:8761"
    api-gateway:
        extends:
            file: ./api-gateway/docker-compose.override.yml
            service: api-gateway
        depends_on:
            - api-nameserver
    app-subscription-service:
        extends:
            file: ./app-subscription-service/docker-compose.override.yml
            service: app-subscription-service
        depends_on:
            - api-nameserver
    api-cache:
        extends:
            file: ./api-cache/docker-compose.override.yml
            service: api-cache
        depends_on:
            - api-nameserver
    rabbitmq:
        image: rabbitmq:management
        ports:
            - "5672:5672"
            - "15672:15672"
        expose:
            - "5672"
            - "15672"
        environment:
            - RABBITMQ_DEFAULT_USER=engsoft2
            - RABBITMQ_DEFAULT_PASS=engsoft2
        networks:
            - main
networks:
    main:
        driver: bridge
