spring:
    cloud:
        gateway:
            routes:
                - id: subscription-service
                  uri: lb://subscription-service
                  predicates:
                      - Path=/servcad/**
                - id: subscription-payment-service
                  uri: lb://subscription-service
                  predicates:
                      - Path=/registrarpagamento/**
                - id: subscription-status-service
                  uri: lb://subscription-status-service
                  predicates:
                      - Path=/assinvalida/**
    application:
        name: api-gateway
server:
    port: 8765
eureka:
    client:
        serviceUrl:
            defaultZone: http://api-nameserver:8761/eureka
            # defaultZone: http://localhost:8761/eureka -> caso rode sem docker
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        gateway:
            enabled: true
