spring:
    cloud:
        gateway:
            routes:
                - id: app-sign-control
                  uri: lb://app-subscription-service:8080
                  predicates:
                      - Path=/servcad/assinaturas/assinvalida/**
    application:
        name: api-gateway
server:
    port: 8765
eureka:
    client:
        serviceUrl:
            defaultZone: http://api-nameserver:8761/eureka
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        gateway:
            enabled: true
