spring:
    cloud:
        gateway:
            routes:
                - id: subscription-service
                  uri: lb://subscription-service
                  predicates:
                      - Path=/servcad/**
                - id: subscription-payment-service
                  uri: lb://subscription-service
                  predicates:
                      - Path=/registrarpagamento/**
                - id: subscription-status-service
                  uri: lb://subscription-status-service
                  predicates:
                      - Path=/assinvalida/**
    application:
        name: subscription-gateway
server:
    port: 8765
eureka:
    client:
        fetch-registry: true
        serviceUrl:
            defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka/}
management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            show-details: always
        gateway:
            enabled: true
