version: "3.8"

services:
    app-subscription-service:
        build: .
        volumes:
            - .:/app
        networks:
            - main
        command: >
            bash -c "chmod +x ./mvnw 
            && ./mvnw spring-boot:run"
        ports:
            - "8080:8080"
        environment:
            - eureka.client.serviceUrl.defaultZone=http://api-nameserver:8761/eureka
networks:
    main:
        driver: bridge
