version: "3.8"

services:
    api-cache:
        build: .
        volumes:
            - .:/app
        networks:
            - main
        command: ./mvnw spring-boot:run
        ports:
            - "8770:8770"
        depends_on:
            - api-nameserver
        environment:
            - eureka.client.serviceUrl.defaultZone=http://api-nameserver:8761/eureka
