version: "3.7"

services:
    api-cache:
        build: .
        volumes:
            - .:/app
        networks:
            - main
        command: >
            bash -c "chmod +x ./mvnw 
            && ./mvnw spring-boot:run"
        ports:
            - 8770
        environment:
            - eureka.client.serviceUrl.defaultZone=http://api-nameserver:8761/eureka/
            - RABBITMQ_SERVICE_URL=rabbitmq
